#!/usr/bin/env python3
"""Train the tiny Roblox bot policy from exported recorder samples.

Usage:
    python tools/bot_training/train_policy.py samples.json --out src/client/Bot/BotPolicyWeights.luau

The input can be the raw JSON printed by the Roblox recorder or an object with
`samples`. This trains a tiny MLP offline so the Roblox client only pays for
cheap inference.
"""

from __future__ import annotations

import argparse
from collections import Counter
import copy
import json
from pathlib import Path


ACTIONS = [
    "Walk",
    "Jump",
    "Vault",
    "HighVault",
    "TrussClimb",
    "Swing",
    "Roll",
    "RollBoost",
    "SlideBoost",
    "Trampoline",
    "Drop",
]


def load_samples(path: Path) -> list[dict]:
    payload = json.loads(path.read_text())
    if isinstance(payload, list):
        return payload
    samples = payload.get("samples", [])
    if not isinstance(samples, list):
        raise ValueError("samples.json must be a JSON list or an object with a samples list")
    return samples


def luau_number(value: float) -> str:
    if abs(value) < 1e-8:
        value = 0.0
    return f"{value:.7g}"


def luau_array(values: list[float], indent: str = "") -> str:
    return "{ " + ", ".join(luau_number(float(value)) for value in values) + " }"


def write_weights(path: Path, mean, std, layers) -> None:
    lines = [
        "--!strict",
        "--[[",
        "    BotPolicyWeights (Client)",
        "    ==============",
        "    Author: Sol (3693744006)",
        "    Updated: 26/07/17",
        "",
        "    Generated by tools/bot_training/train_policy.py.",
        "]]",
        "",
        "return table.freeze({",
        "\tversion = 2,",
        f"\tinputSize = {len(mean)},",
        "\tactions = table.freeze({",
    ]
    for action in ACTIONS:
        lines.append(f'\t\t"{action}",')
    lines += [
        "\t}),",
        f"\tinputMean = table.freeze({luau_array(mean)}),",
        f"\tinputStd = table.freeze({luau_array(std)}),",
        "\tlayers = table.freeze({",
    ]

    for layer_index, layer in enumerate(layers):
        activation = "relu" if layer_index < len(layers) - 1 else "linear"
        lines += [
            "\t\ttable.freeze({",
            f'\t\t\tactivation = "{activation}",',
            "\t\t\tweights = table.freeze({",
        ]
        for row in layer["weights"]:
            lines.append(f"\t\t\t\ttable.freeze({luau_array(row)}),")
        lines += [
            "\t\t\t}),",
            f"\t\t\tbias = table.freeze({luau_array(layer['bias'])}),",
            "\t\t}),",
        ]

    lines += [
        "\t}),",
        "})",
        "",
    ]
    path.write_text("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("samples", type=Path)
    parser.add_argument("--out", type=Path, default=Path("src/client/Bot/BotPolicyWeights.luau"))
    parser.add_argument("--epochs", type=int, default=240)
    parser.add_argument("--hidden", type=int, default=24)
    parser.add_argument("--seed", type=int, default=3693744006)
    args = parser.parse_args()

    samples = [
        sample
        for sample in load_samples(args.samples)
        if isinstance(sample, dict)
        and isinstance(sample.get("features"), list)
        and sample.get("action") in ACTIONS
    ]
    if not samples:
        raise SystemExit("No valid samples found.")

    action_counts = Counter(str(sample["action"]) for sample in samples)
    if len(action_counts) < 2:
        only_action = next(iter(action_counts))
        raise SystemExit(
            f"Refusing to train a one-action policy ({only_action}: {action_counts[only_action]} samples). "
            "Collect validated tech exploration or player demonstrations first."
        )

    try:
        import torch
        import torch.nn as nn
    except ImportError as exc:
        raise SystemExit("PyTorch is required for offline training: pip install torch") from exc

    torch.manual_seed(args.seed)
    x = torch.tensor([sample["features"] for sample in samples], dtype=torch.float32)
    action_indexes = torch.tensor([ACTIONS.index(sample["action"]) for sample in samples], dtype=torch.long)
    rewards = torch.tensor([float(sample.get("reward", 0)) for sample in samples], dtype=torch.float32)
    evidence_weights = torch.tensor(
        [max(0.1, min(3.0, float(sample.get("weight", 1)))) for sample in samples],
        dtype=torch.float32,
    )
    class_weights = torch.tensor(
        [
            (len(samples) / (len(action_counts) * action_counts[str(sample["action"])])) ** 0.5
            for sample in samples
        ],
        dtype=torch.float32,
    ).clamp(0.4, 3.0)
    sample_weights = evidence_weights * class_weights

    sample_indexes = torch.arange(len(samples))
    validation_mask = sample_indexes.remainder(5).eq(0)
    training_mask = ~validation_mask
    if validation_mask.sum().item() == 0 or training_mask.sum().item() == 0:
        raise SystemExit("Not enough samples for the deterministic validation split.")

    mean = x[training_mask].mean(dim=0)
    std = x[training_mask].std(dim=0).clamp_min(0.05)
    x = (x - mean) / std

    model = nn.Sequential(
        nn.Linear(x.shape[1], args.hidden),
        nn.ReLU(),
        nn.Linear(args.hidden, len(ACTIONS)),
    )
    optimizer = torch.optim.AdamW(model.parameters(), lr=0.003, weight_decay=0.0005)

    def weighted_loss(mask):
        scores = model(x[mask])
        selected_actions = action_indexes[mask]
        chosen_scores = scores.gather(1, selected_actions.view(-1, 1)).squeeze(1)
        squared_error = (chosen_scores - rewards[mask].clamp(-8, 8)) ** 2
        selected_weights = sample_weights[mask]
        loss = (squared_error * selected_weights).sum() / selected_weights.sum().clamp_min(1)
        return loss + 0.001 * (scores ** 2).mean()

    best_validation_loss = float("inf")
    best_state = None
    for epoch in range(args.epochs):
        loss = weighted_loss(training_mask)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if epoch % 5 == 0 or epoch == args.epochs - 1:
            model.eval()
            with torch.no_grad():
                validation_loss = float(weighted_loss(validation_mask).item())
            model.train()
            if validation_loss < best_validation_loss:
                best_validation_loss = validation_loss
                best_state = copy.deepcopy(model.state_dict())

    if best_state is None:
        raise SystemExit("Training produced no valid checkpoint.")
    model.load_state_dict(best_state)
    model.eval()
    with torch.no_grad():
        training_loss = float(weighted_loss(training_mask).item())

    layers = []
    for module in model:
        if isinstance(module, nn.Linear):
            layers.append({
                "weights": module.weight.detach().cpu().tolist(),
                "bias": module.bias.detach().cpu().tolist(),
            })

    write_weights(args.out, mean.detach().cpu().tolist(), std.detach().cpu().tolist(), layers)
    print(
        f"Wrote {args.out} from {len(samples)} samples "
        f"(train loss {training_loss:.4f}, validation loss {best_validation_loss:.4f})."
    )
    print("Action counts: " + ", ".join(f"{action}={action_counts[action]}" for action in ACTIONS if action_counts[action]))


if __name__ == "__main__":
    main()
